export const MenuItem = [
  {
    id: '1',
    title: 'Healthy Meal Plan',
    description: 'How we dream about our future',
    img: 'breakfast1.png',
    price: '30',
    details: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. `,
  },
  {
    id: '2',
    title: 'Fried Chicken Bento',
    description: 'How we dream about our future',
    img: 'breakfast2.png',
    price: '40',
    details: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. `,
  },
  {
    id: '3',
    title: 'Teraggon Rubbed Salmon',
    description: 'How we dream about our future',
    img: 'breakfast3.png',
    price: '50',
    details: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. `,
  },
  {
    id: '4',
    title: 'Oatmeal Almond Milk',
    description: 'How we dream about our future',
    img: 'breakfast4.png',
    price: '60',
    details: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. `,
  },
  {
    id: '5',
    title: 'Masala Puris Served',
    description: 'How we dream about our future',
    img: 'breakfast5.png',
    price: '70',
    details: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. `,
  },
  {
    id: '6',
    title: 'Jowar Pyaz Ki Roti',
    description: 'How we dream about our future',
    img: 'breakfast6.png',
    price: '80',
    details: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. `,
  },
  {
    id: '7',
    title: 'Lunch Roti',
    description: 'How we dream about our future',
    img: 'lunch1.png',
    price: '80',
    details: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. `,
  },
  {
    id: '8',
    title: 'Lunch Paratha',
    description: 'How we dream about our future',
    img: 'lunch2.png',
    price: '80',
    details: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. `,
  },
  {
    id: '9',
    title: 'Lunch Sabzi',
    description: 'How we dream about our future',
    img: 'lunch3.png',
    price: '80',
    details: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. `,
  },
  {
    id: '10',
    title: 'Lunch Pulao Rice',
    description: 'How we dream about our future',
    img: 'lunch4.png',
    price: '80',
    details: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. `,
  },
  {
    id: '11',
    title: 'Lunch Biryani',
    description: 'How we dream about our future',
    img: 'lunch5.png',
    price: '80',
    details: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. `,
  },
  {
    id: '12',
    title: 'Lunch Salad',
    description: 'How we dream about our future',
    img: 'lunch6.png',
    price: '80',
    details: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. `,
  },
  {
    id: '13',
    title: 'Hard tacos or tostadas',
    description: 'How we dream about our future',
    img: 'dinner1.png',
    price: '80',
    details: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. `,
  },
  {
    id: '14',
    title: 'Huevos rancheros',
    description: 'How we dream about our future',
    img: 'dinner2.png',
    price: '80',
    details: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. `,
  },
  {
    id: '15',
    title: 'Stir fry',
    description: 'How we dream about our future',
    img: 'dinner3.png',
    price: '80',
    details: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. `,
  },
  {
    id: '16',
    title: 'Burritos',
    description: 'How we dream about our future',
    img: 'dinner4.png',
    price: '80',
    details: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. `,
  },
  {
    id: '17',
    title: 'Fajitas',
    description: 'How we dream about our future',
    img: 'dinner5.png',
    price: '80',
    details: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. `,
  },
  {
    id: '18',
    title: 'Burgers or hotdogs',
    description: 'How we dream about our future',
    img: 'dinner6.png',
    price: '80',
    details: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. `,
  },
];
